.TH "/media/solidity/DATA/Code/bonedaddy/ulog/src Directory Reference" 3 "Tue Dec 15 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/ulog/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolors\&.c\fP"
.br
.ti -1c
.RI "file \fBlogger\&.c\fP"
.br
.RI "a thread safe logger with optional printf style logging "
.in -1c
