.TH "/media/solidity/DATA/Code/bonedaddy/ulog/docs/front_page.md" 3 "Thu Aug 13 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/ulog/docs/front_page.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ulogger from the source code\&.
