.TH "thread_logger" 3 "Thu Aug 20 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBdebug\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.RI "indicates whether we will action on debug logs "
.ti -1c
.RI "\fBmutex_fn\fP \fBlock\fP"
.br
.RI "used for synchronization across threads "
.ti -1c
.RI "\fBmutex_fn\fP \fBunlock\fP"
.br
.RI "helper function for pthread_mutex_lock "
.ti -1c
.RI "\fBlog_fn\fP \fBlog\fP"
.br
.RI "helper function for pthread_mutex_unlock "
.ti -1c
.RI "\fBlog_fnf\fP \fBlogf\fP"
.br
.RI "function that gets called for all regular logging "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file logger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool thread_logger::debug"

.PP
Definition at line 211 of file logger\&.h\&.
.SS "\fBmutex_fn\fP thread_logger::lock"

.PP
used for synchronization across threads 
.PP
Definition at line 213 of file logger\&.h\&.
.SS "\fBlog_fn\fP thread_logger::log"

.PP
helper function for pthread_mutex_unlock 
.PP
Definition at line 215 of file logger\&.h\&.
.SS "\fBlog_fnf\fP thread_logger::logf"

.PP
function that gets called for all regular logging 
.PP
Definition at line 217 of file logger\&.h\&.
.SS "pthread_mutex_t thread_logger::mutex"

.PP
indicates whether we will action on debug logs 
.PP
Definition at line 212 of file logger\&.h\&.
.SS "\fBmutex_fn\fP thread_logger::unlock"

.PP
helper function for pthread_mutex_lock 
.PP
Definition at line 214 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ulogger from the source code\&.
