.TH "/media/solidity/DATA/Code/bonedaddy/ulog/include/version.h" 3 "Thu Aug 20 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/bonedaddy/ulog/include/version.h \- provides release version information as a macro  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
provides release version information as a macro 


.PP
\fBAuthor\fP
.RS 4
Bonedaddy
.RE
.PP
dedicated file containing the current version of ulog as a macro
.PP
largely used to make it easy to verify what version of the library you are using 
.PP
Definition in file \fBversion\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ulogger from the source code\&.
