.TH "file_logger" 3 "Thu Aug 13 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "\fBthread_logger\fP * \fBthl\fP"
.br
.RI "the file descriptor used for sending log information to "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 196 of file logger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int file_logger::fd"

.PP
Definition at line 197 of file logger\&.h\&.
.SS "\fBthread_logger\fP* file_logger::thl"

.PP
the file descriptor used for sending log information to 
.PP
Definition at line 198 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ulogger from the source code\&.
