.TH "file_logger" 3 "Mon Aug 10 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthread_logger\fP * \fBthl\fP"
.br
.ti -1c
.RI "int \fBfd\fP"
.br
.RI "the underlying threadsafe logger used for sycnhronization and the actual logging "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 120 of file logger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int file_logger::fd"

.PP
the underlying threadsafe logger used for sycnhronization and the actual logging 
.PP
Definition at line 123 of file logger\&.h\&.
.SS "\fBthread_logger\fP* file_logger::thl"

.PP
Definition at line 121 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ulogger from the source code\&.
