.TH "todo" 3 "Tue Aug 11 2020" "ulogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBlogger\&.c\fP \fP" 1c
.IP "\(bu" 2
buffer logs and use a dedicated thread for writing (avoid blocking locks)
.IP "\(bu" 2
handling system signals (exit, kill, etc\&.\&.\&.)  
.PP
.IP "\fBFile \fBlogger\&.h\fP \fP" 1c
.IP "\(bu" 2
buffer logs and use a dedicated thread for writing (avoid blocking locks)
.IP "\(bu" 2
handling system signals (exit, kill, etc\&.\&.\&.) 
.PP
.PP

